# Generated by Django 5.2.17 on 2026-10-09 09:09
# A data migration: it changes rows, not the table. Written by hand on purpose.

from django.conf import settings
from django.db import migrations


def give_old_todos_an_owner(apps, schema_editor):
    """Give every to-do with no owner to the oldest superuser (admin account)."""
    Todo = apps.get_model("todos", "Todo")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    old_todos = Todo.objects.filter(owner__isnull=True)
    if not old_todos.exists():
        return
    admin = User.objects.filter(is_superuser=True).order_by("pk").first()
    if admin is None:
        raise RuntimeError(
            "There are to-dos with no owner, and no admin account to give them to. "
            "Run `uv run python manage.py createsuperuser`, then `migrate` again."
        )
    old_todos.update(owner=admin)


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_todo_owner"),
    ]

    operations = [
        migrations.RunPython(give_old_todos_an_owner, migrations.RunPython.noop),
    ]
