# Generated by Django 5.2.17 on 2026-10-09 09:51
# A data migration: it changes rows, not the table. Written by hand on purpose.
# 0005_todolist, this file and 0007_todo_list_required are a set: keep all three.

from django.conf import settings
from django.db import migrations


def give_each_user_a_list(apps, schema_editor):
    """Give every user an "Inbox" list, and put their to-dos in it."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    TodoList = apps.get_model("todos", "TodoList")
    Todo = apps.get_model("todos", "Todo")
    for user in User.objects.all():
        todo_list = TodoList.objects.create(owner=user, name="Inbox")
        Todo.objects.filter(owner=user).update(todo_list=todo_list)


def copy_owner_back(apps, schema_editor):
    """Going back: each to-do's owner is the owner of its list."""
    Todo = apps.get_model("todos", "Todo")
    for todo in Todo.objects.select_related("todo_list"):
        todo.owner_id = todo.todo_list.owner_id
        todo.save(update_fields=["owner"])


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0005_todolist"),
    ]

    operations = [
        migrations.RunPython(give_each_user_a_list, copy_owner_back),
    ]
