# Generated by Django 5.2.17 on 2026-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0007_todo_list_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
