# Generated by Django 5.2.17 on 2026-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
