# Generated by Django 5.2.17 on 2026-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
