# Generated by Django 5.2.17 on 2026-10-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat',
            field=models.CharField(blank=True, choices=[('', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeated_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_copy', to='todos.todo'),
        ),
    ]
