# Generated by Django 5.2.17 on 2026-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
