# Generated by Django 5.2.17 on 2026-10-10 13:51
# A data migration: it changes rows, not the table. Written by hand on purpose.
# 0015_todo_position and this file are a set: keep both.

from django.db import migrations


def fill_position(apps, schema_editor):
    """Number the to-dos of each list 1, 2, 3, ... in the order they were made.

    So the manual order starts out the same as "oldest first". It uses the
    model as it was at this migration (apps.get_model), never todos.models.
    """
    Todo = apps.get_model("todos", "Todo")
    current_list = None
    number = 0
    for todo in Todo.objects.order_by("todo_list_id", "created_at", "pk"):
        if todo.todo_list_id != current_list:
            current_list, number = todo.todo_list_id, 0
        number += 1
        todo.position = number
        todo.save(update_fields=["position"])


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0015_todo_position"),
    ]

    operations = [
        # Going back needs nothing: 0015 going back drops the field.
        migrations.RunPython(fill_position, migrations.RunPython.noop),
    ]
