# Generated by Django 5.2.17 on 2026-10-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_fill_todo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminded_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
